# Generated by Django 4.1.5 on 2023-01-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountOfCards', models.IntegerField()),
                ('deckName', models.CharField(default='', max_length=30)),
                ('deckID', models.CharField(max_length=10, unique=True)),
                ('deckCreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
