# Generated by Django 4.1.5 on 2023-01-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deckID',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
