# Generated by Django 4.1.5 on 2023-01-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_deck_deckid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='amountOfCards',
        ),
    ]
